### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by mrxiaozhuox** [arqalite/dioxus-cli-tailwind-plugin#1]
I want to change the repo name to `tailwind-plugin`

**Comment by arqalite** [comment]
Sure, you can change it (and I'll update the README to use the new repo name).

**Comment by mrxiaozhuox** [comment]
Thank you!

**Comment by arqalite** [comment]
I can't seem to be able to change the name myself - I lack permissions I guess? If you have the time, please change it (or assign me permissions if you want).

**Comment by mrxiaozhuox** [comment]
> I can't seem to be able to change the name myself - I lack permissions I guess? If you have the time, please change it (or assign me permissions if you want).

I have already given you admin permission.
